name: terraform-nightmayr
base: core18
adopt-info: terraform
summary: Build, change, and version infrastructure safely and efficiently
description: |
  Terraform is a tool for building, changing, and versioning infrastructure safely and efficiently. 
  Terraform can manage existing and popular service providers as well as custom in-house solutions.

grade: stable
confinement: strict
license: MPL-2.0

apps:
  terraform:
    command: bin/terraform
    plugs:
      - home
      - network
      - network-bind
parts:
  terraform:
    source: https://github.com/hashicorp/terraform.git
    plugin: go
    go-importpath: github.com/hashicorp/terraform
    go-buildtags:
      - terraform
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git tag | grep v0.13 | sort | tail -1)"
      last_released_tag="$(snap info terraform-nightmayr | awk '$1 == "latest/beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git checkout "${last_committed_tag}"
        cd ../src
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version `echo ${last_committed_tag} | sed "s/v//g"`